---
- hosts: dev
  become: True 
  tasks:
    - name: install amazon-linux-extras
      shell: yum -y install amazon-linux-extras

    - name: docker setup
      shell: amazon-linux-extras install docker -y

    - name: start the service
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: docker run user
      shell: usermod -a -G docker ec2-user

    - name: check docker version
      command: "docker version"
      register: docversion
      
    - name: start the container
      docker_container:
        name: newapp
        image: "incharacr/newapp:0.0.1"
        state: started
        published_ports:
          -0.0.0.0:80808:8080
      
    
