---
- hosts: dev
  become: True 
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
        
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
        
    - name: install amazon-linux-extras
      shell: yum -y install amazon-linux-extras

    - name: docker setup
      shell: amazon-linux-extras install docker -y

    - name: start the service
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: docker run user
      shell: usermod -a -G docker ec2-user

    - name: check docker version
      command: "docker version"
      register: docversion
      
    - name: start the container
      docker_container:
        name: project-app
        image: "incharacr/project-app:0.0.1"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
      
    
